---
- name: Add ppa Repository
  become: yes
  apt_repository: repo=ppa:ondrej/{{ php.ppa }}

- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install PHP
  become: yes
  apt: pkg=php7.1 state=latest

- name: install PHP packages
  become: yes
  apt: pkg="{{ item }}" state=latest
  with_items:
    - php7.1-fpm
    - php7.1-cli
    - php7.1-common
    - php7.1-curl
    - php7.1-json
    - php7.1-gd
    - php7.1-mcrypt
    - php7.1-odbc
    - php7.1-pgsql
    - php7.1-mbstring
    - php7.1-mysql
    - php7.1-xmlrpc
    - php7.1-opcache
    - php7.1-intl
    - php7.1-bz2
    - php7.1-xml
