Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_version = "20171025.0.0"
  # ipは適宜変更
  config.vm.network :private_network, ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "default"
    # メモリ割り当て
    vb.cpus = 2
    vb.memory = 2048
    ##vb.ioapic = 'on'
  end

  # ssh
  config.ssh.username = "ubuntu"
  config.ssh.password = "c647609bc20d739b829f52b4"

  # プロビジョニング
  # privileged trueにするとrootユーザで実行されるためhomeディレクトリなどが想定外のものになる
  config.vm.provision "shell", :path => "ansible/provision_init.sh", :privileged => false
  # 共有ディレクトリ
  config.vm.synced_folder "./ansible", "/vagrant/ansible", type: "nfs"
end
