Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  # ipは適宜変更
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "default"
    # メモリ割り当て
    vb.cpus = 2
    vb.memory = 2048
    ##vb.ioapic = 'on'
  end

  # プロビジョニング
  # privileged trueにするとrootユーザで実行されるためhomeディレクトリなどが想定外のものになる
  #config.vm.provision "shell", :path => "ansible/provision_init.sh", :privileged => false
  # 共有ディレクトリ
  config.vm.synced_folder "./ansible", "/vagrant/ansible", type: "nfs"
end
