Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_version = "20181113.0.0"
  config.vm.hostname = "vagrant-local-ubuntu16"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu16"
    # メモリ割り当て
    vb.cpus = 2
    vb.memory = 2048
    ##vb.ioapic = 'on'
  end

  # プロビジョニング
  # privileged trueにするとrootユーザで実行されるためhomeディレクトリなどが想定外のものになる
  config.vm.provision "shell", :path => "ansible/provision_init.sh", :privileged => false
  # 共有ディレクトリ
  config.vm.synced_folder "./ansible", "/vagrant/ansible", type: "nfs"
  config.vm.synced_folder "./mnt", "/vagrant/mnt", type: "nfs"
end
