Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_version = "20181113.0.0"
  # ホスト OS 内でユニークであること
  config.vm.hostname = "vagrant-local-ubuntu16"
  # 他の vm とかぶらないようなアドレスを設定する
  # config.vm.network :private_network, ip: "192.168.33.10"
  # webpack-dev-server 用の設定
  # config.vm.network "forwarded_port", guest: 8881, host: 8881
  # ホスト OS 側の ssh-agent 設定を引き継ぐ。ただし、 vagrant ssh のときしか適用されない。 ssh vagrant@192.168.... の場合は適用できないので provision 時に回避策を講じている
  config.ssh.forward_agent = true

  config.vm.provider "virtualbox" do |vb|
    # VirtualBox GUI 上の表示名
    vb.name = "ubuntu16"
    # メモリ割り当て
    vb.cpus = 2
    vb.memory = 2048
    ##vb.ioapic = 'on'
  end

  # プロビジョニング
  # privileged trueにするとrootユーザで実行されるためhomeディレクトリなどが想定外のものになる
  config.vm.provision "shell", :path => "./ansible/provision_init.sh", :privileged => false
  # 共有ディレクトリ
  config.vm.synced_folder "./ansible", "/vagrant/ansible", type: "nfs"
  config.vm.synced_folder "./mnt", "/vagrant/mnt", type: "nfs"
end
